version: "3.7"
services:
  php:
    build:
      args:
        uname: ${PHP_UNAME}
        uid: ${PHP_UID}
        gid: ${PHP_GID}
      context: ./compose/php
    image: photos_exchanger
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - main_network
    depends_on:
      - db
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - ${DB_LOCAL_PORT}:3306
    volumes:
      - ./compose/database/dump:/var/lib/mysql
    networks:
      - main_network
  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - ${NGINX_LOCAL_PORT}:80
    volumes:
      - ../:/var/www
      - ./compose/nginx:/etc/nginx/conf.d
    networks:
      - main_network
    depends_on:
      - php
networks:
  main_network:
    driver: bridge
